site_name: Building RESTful API with Symfony and PHP 8

theme:
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  features:
    - search.suggest
    - navigation.expand
    - navigation.indexes
    # - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt 

markdown_extensions:
  - meta
  - toc:
      toc_depth: 3
      permalink: true      
plugins:
  - search
  - git-revision-date    
  
nav:
  - Preface:
    - index.md   
  - Getting Started:
    - gs/index.md
    - Prerequisites: gs/pre.md
    - "Creating Symfony Project": gs/create.md
    - "Hello Symfony!": gs/hello.md
  - Data Accessing with Doctrine:
    - data/index.md
    - "Connecting to Database": data/connect.md
    - "Data Modeling": data/model.md
    - "Data Operations": data/operations.md
  - Producing RESTful API:
    - api/index.md
    - "Creating Controller": api/postctl.md
    - "Handling Exceptions": api/ex.md
    - "Handling Subresources": api/sub.md
    - "API Design Consideration": api/design.md
  - Testing:
    - test/index.md
    - "Testing Repository": test/testdb.md
    - "Testing Controller": test/testctl.md   
  - Tips and Tricks:
    - tips/index.md
    - "Using Enum": tips/enum.md   
    